### ISSUE TITLE
Emulate by setting timestamps?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [awesome-inc/monorepo.gitlab#3]
I did something like this, but tried to basically store all timestamps of `git ls-files` in the and then re-apply them so that `make`-like tools could work out-of-the-box.

Specifying dependencies explicitly is good hygiene, but using timestamps could be easier to convert to if it can be made to work.

**Comment by mkoertgen** [comment]
Nice idea. Could you provide an example?
