### ISSUE TITLE
jq doesn't work as expected

### ISSUE THREAD

**Issue by maxpavlov** [awesome-inc/monorepo.gitlab#5]
When my script tries to define a last green commit, it fails with this error logged:

`$ .monorepo.gitlab/last_green_commit.sh
~/builds/83c30a16/0/SKBX/infrastructure.warp/.monorepo.gitlab ~/builds/83c30a16/0/SKBX/infrastructure.warp
jq: error (at <stdin>:0): Cannot index string with string "sha"
Last green commit is ''.`

Although jq.filter in being pulled down as a submodule.

curl, jq and PRIVATE_TOKEN ENV are fine. Please assist on how to troubleshoot.

**Comment by mkoertgen** [comment]
Seems as if the curl command failed or no green pipeline so far at all. The error message indicates that the curl output either contains no valid json or no array entries with `success`, so the `sha`-property cannot be selected.

Did you set the `CI_SERVER_URL` correctly?

Check the output of

```bash
curl -s ${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/pipelines?private_token=${PRIVATE_TOKEN}
```

Does it contain any pipelines with `success`?

**Comment by maxpavlov** [comment]
@mkoertgen, thank you. I've echoed the url in the pipeline, checked the browser output and found out that the token I am supplying via a variable needs "api" permission. After getting the script a correct token, it worked like a charm.
