### ISSUE TITLE
jq doesn't work as expected

### ISSUE THREAD

**Issue by tibers** [awesome-inc/monorepo.gitlab#8]
It's definitely this one again: https://github.com/awesome-inc/monorepo.gitlab/issues/5

However I have manually created a private token and attempted to use `last_green_commit.sh` just by walking through it in a shell and the output of `curl` is:
`<html><body>You are being <a href="https://gitlab.MYJOB.net/users/sign_in">redirected</a>.</body></html>`.

```
jq: error (at <stdin>:0): Cannot index string with string "sha"
Last green commit is ''.
```

I do not have 2FA enabled, and gitlab is LDAP enabled, if it helps.

**EDIT:** possibly related, we don't have `/projects/` in our path, but removing it doesn't seem to improve things any.

**Comment by mkoertgen** [comment]
@tibers Is the url correct: `https://gitlab.MYJOB.net/` ? Maybe you need to set your custom gitlab url in `gitlab-ci.yml`. 

Here is an example:

- https://github.com/awesome-inc/hello.gitlab.monorepo/blob/master/.gitlab-ci.yml#L6

**Comment by tibers** [comment]
Same behavior with `CI_SERVER_URL` set to https://gitlab.MYJOB.net/ ...

```
$ /bin/bash -c ".monorepo.gitlab/last_green_commit.sh ; source $CI_PROJECT_DIR/helpers.sh && for_each_project && build_if_changed"
/builds/openstack/project-pipeline/projects/.monorepo.gitlab /builds/openstack/project-pipeline/projects
jq: error (at <stdin>:0): Cannot index string with string "sha"
Last green commit is ''.
```

**Comment by mkoertgen** [comment]
Hm, i need to guess. Maybe the gitlab version is too old (should be 11+)?

**Comment by tibers** [comment]
We're running GitLab Enterprise Edition 11.10.6-ee. If you don't want to guess I can privately share code if you send a mail to josh.knarr@gmail.com - I also tried changing `PRIVATE-TOKEN` to `Private-Token` to match the docs in gitlab but HTTP headers are case insensitive anyway and it didn't work.

**Comment by tibers** [comment]
Alpine containers now work correctly. Thanks for accepting that MR!
